version: 0.2
phases:
 pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore SchoolProject/SchoolProject.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output SchoolProject/SchoolProject.csproj
artifacts:
  files:
    - SchoolProject/build_output/**/*
